/*
 * Copyright (c) 2015-2022 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP OCPI <https://github.com/OpenChargingCloud/WWCP_OCPI>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace cloud.charging.open.protocols.OCPIv2_1_1
{

    /// <summary>
    /// ISO 639-1 codes for languages.
    /// http://www.loc.gov/standards/iso639-1/php/code_list.php
    /// </summary>
    public enum Languages
    {

        unknown,

        aa,
        ab,
        ae,
        af,
        ak,
        am,
        an,
        ar,
        @as,
        av,
        ay,
        az,
        ba,
        be,
        bg,
        bh,
        bi,
        bm,
        bn,
        bo,
        br,
        bs,
        ca,
        ce,
        ch,
        co,
        cr,
        cs,
        cu,
        cv,
        cy,
        da,
        de,
        dv,
        dz,
        ee,
        el,
        en,
        eo,
        es,
        et,
        eu,
        fa,
        ff,
        fi,
        fj,
        fo,
        fr,
        fy,
        ga,
        gd,
        gl,
        gn,
        gu,
        gv,
        ha,
        he,
        hi,
        ho,
        hr,
        ht,
        hu,
        hy,
        hz,
        ia,
        id,
        ie,
        ig,
        ii,
        ik,
        io,
        @is,
        it,
        iu,
        ja,
        jv,
        ka,
        kg,
        ki,
        kj,
        kk,
        kl,
        km,
        kn,
        ko,
        kr,
        ks,
        ku,
        kv,
        kw,
        ky,
        la,
        lb,
        lg,
        li,
        ln,
        lo,
        lt,
        lu,
        lv,
        mg,
        mh,
        mi,
        mk,
        ml,
        mn,
        mr,
        ms,
        mt,
        my,
        na,
        nb,
        nd,
        ne,
        ng,
        nl,
        nn,
        no,
        nr,
        nv,
        ny,
        oc,
        oj,
        om,
        or,
        os,
        pa,
        pi,
        pl,
        ps,
        pt,
        qu,
        rm,
        rn,
        ro,
        ru,
        rw,
        sa,
        sc,
        sd,
        se,
        sg,
        si,
        sk,
        sl,
        sm,
        sn,
        so,
        sq,
        sr,
        ss,
        st,
        su,
        sv,
        sw,
        ta,
        te,
        tg,
        th,
        ti,
        tk,
        tl,
        tn,
        to,
        tr,
        ts,
        tt,
        tw,
        ty,
        ug,
        uk,
        ur,
        uz,
        ve,
        vi,
        vo,
        wa,
        wo,
        xh,
        yi,
        yo,
        za,
        zh,
        zu

    }

}
