/*
 * Copyright (c) 2015-2022 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP OCPI <https://github.com/OpenChargingCloud/WWCP_OCPI>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace cloud.charging.open.protocols.OCPIv2_1_1
{

    /// <summary>
    /// Token types.
    /// </summary>
    public enum TokenTypes
    {

        /// <summary>
        /// One time use Token ID generated by a server (or App.) The eMSP uses this to bind a Session to a customer, probably an app user.
        /// </summary>
        AD_HOC_USER,

        /// <summary>
        /// Token ID generated by a server (or App.) to identify a user of an App. The same user uses the same Token for every Session.
        /// </summary>
        APP_USER,

        /// <summary>
        /// Other type of token.
        /// </summary>
        OTHER,

        /// <summary>
        /// RFID Token.
        /// </summary>
        RFID

    }

}
